/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author xyh10
 */
import Model.Person;
import Model.Address;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */

    Person person;
    
    public NewJFrame() {
        initComponents(); 
         this.person = new Person();
    }
    
    public void display(){
        viewNUID.setText(person.getNUID());
        viewFirstName.setText(person.getFirstName());
        viewLastName.setText(person.getLastName());
        viewCollegeName.setText(person.getCollegeName());
        
        viewPhoneNumber.setText(person.getPhoneNumber());
        viewEmailAddress.setText(person.getEmailAddress());
        
        viewStreetName.setText(person.getAddress().getStreetName());
        viewAprtNumber.setText(person.getAddress().getApartmentNo());
        viewCity.setText(person.getAddress().getCity());
        viewZipCode.setText(person.getAddress().getZipCode());
        
        
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        SaveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldNUID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldCollegeName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fieldPhoneNumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fieldEmailAddress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fieldStreetName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fieldAprtNumber = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fieldCity = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fieldZipCode = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        fieldFirstName = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        rightPanel = new javax.swing.JPanel();
        viewFirstName = new javax.swing.JLabel();
        viewLastName = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        viewNUID = new javax.swing.JLabel();
        viewCollegeName = new javax.swing.JLabel();
        viewPhoneNumber = new javax.swing.JLabel();
        viewEmailAddress = new javax.swing.JLabel();
        viewStreetName = new javax.swing.JLabel();
        viewAprtNumber = new javax.swing.JLabel();
        viewCity = new javax.swing.JLabel();
        viewZipCode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(812, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSplitPane1.setMinimumSize(new java.awt.Dimension(805, 600));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(805, 600));

        leftPanel.setBackground(new java.awt.Color(0, 255, 255));
        leftPanel.setMinimumSize(new java.awt.Dimension(300, 600));
        leftPanel.setPreferredSize(new java.awt.Dimension(300, 600));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        leftPanel.add(SaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("First Name");
        leftPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Last Name");
        leftPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("NUID");
        leftPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        fieldNUID.setBackground(new java.awt.Color(255, 255, 255));
        fieldNUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNUIDActionPerformed(evt);
            }
        });
        leftPanel.add(fieldNUID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 130, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("College Name");
        leftPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        fieldCollegeName.setBackground(new java.awt.Color(255, 255, 255));
        leftPanel.add(fieldCollegeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 130, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Contact Information");
        leftPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 20));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Phone number");
        leftPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        fieldPhoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        leftPanel.add(fieldPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 130, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("email Address");
        leftPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        fieldEmailAddress.setBackground(new java.awt.Color(255, 255, 255));
        leftPanel.add(fieldEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 130, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Adress Information");
        leftPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Street Name");
        leftPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        fieldStreetName.setBackground(new java.awt.Color(255, 255, 255));
        fieldStreetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldStreetNameActionPerformed(evt);
            }
        });
        leftPanel.add(fieldStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 130, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Apartment Number");
        leftPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        fieldAprtNumber.setBackground(new java.awt.Color(255, 255, 255));
        leftPanel.add(fieldAprtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 130, -1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("City/State");
        leftPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        fieldCity.setBackground(new java.awt.Color(255, 255, 255));
        leftPanel.add(fieldCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 130, -1));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Zip Cpde");
        leftPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        fieldZipCode.setBackground(new java.awt.Color(255, 255, 255));
        leftPanel.add(fieldZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 130, -1));

        jLabel24.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Personal Information");
        leftPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        fieldFirstName.setBackground(new java.awt.Color(255, 255, 255));
        fieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFirstNameActionPerformed(evt);
            }
        });
        leftPanel.add(fieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 130, -1));

        fieldLastName.setBackground(new java.awt.Color(255, 255, 255));
        leftPanel.add(fieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 130, -1));

        jSplitPane1.setLeftComponent(leftPanel);

        rightPanel.setBackground(new java.awt.Color(102, 255, 153));
        rightPanel.setMinimumSize(new java.awt.Dimension(500, 600));
        rightPanel.setPreferredSize(new java.awt.Dimension(500, 600));
        rightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewFirstName.setBackground(new java.awt.Color(255, 255, 255));
        viewFirstName.setOpaque(true);
        rightPanel.add(viewFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 250, 20));

        viewLastName.setBackground(new java.awt.Color(255, 255, 255));
        viewLastName.setOpaque(true);
        rightPanel.add(viewLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 250, 20));

        jLabel26.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Personal Information");
        rightPanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("NUID");
        rightPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("First Name");
        rightPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Last Name");
        rightPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("College Name");
        rightPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel17.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Contact Information");
        rightPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 20));

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Phone number");
        rightPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("email Address");
        rightPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel20.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Adress Information");
        rightPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Street Name");
        rightPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Apartment Number");
        rightPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("City/State");
        rightPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Zip Cpde");
        rightPanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        viewNUID.setBackground(new java.awt.Color(255, 255, 255));
        viewNUID.setOpaque(true);
        rightPanel.add(viewNUID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 250, 20));

        viewCollegeName.setBackground(new java.awt.Color(255, 255, 255));
        viewCollegeName.setOpaque(true);
        rightPanel.add(viewCollegeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 250, 20));

        viewPhoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        viewPhoneNumber.setOpaque(true);
        rightPanel.add(viewPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 250, 20));

        viewEmailAddress.setBackground(new java.awt.Color(255, 255, 255));
        viewEmailAddress.setOpaque(true);
        rightPanel.add(viewEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 250, 20));

        viewStreetName.setBackground(new java.awt.Color(255, 255, 255));
        viewStreetName.setOpaque(true);
        rightPanel.add(viewStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 250, 20));

        viewAprtNumber.setBackground(new java.awt.Color(255, 255, 255));
        viewAprtNumber.setOpaque(true);
        rightPanel.add(viewAprtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 250, 20));

        viewCity.setBackground(new java.awt.Color(255, 255, 255));
        viewCity.setOpaque(true);
        rightPanel.add(viewCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 250, 20));

        viewZipCode.setBackground(new java.awt.Color(255, 255, 255));
        viewZipCode.setOpaque(true);
        rightPanel.add(viewZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 250, 20));

        jSplitPane1.setRightComponent(rightPanel);

        getContentPane().add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 812, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        person.setNUID(fieldNUID.getText());
        person.setFirstName(fieldFirstName.getText());
        person.setLastName(fieldLastName.getText());
       
        person.setPhoneNumber(fieldPhoneNumber.getText());
        person.setEmailAddress(fieldEmailAddress.getText());
        person.setCollegeName(fieldCollegeName.getText());
        
        
        Address address = person.getAddress();
        address.setStreetName(fieldStreetName.getText());
        address.setApartmentNo(fieldAprtNumber.getText());
        address.setCity(fieldCity.getText());
        
        address.setZipCode(fieldZipCode.getText());
//        address.setApartmentNo(apartmentNo);
        display();

        
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void fieldStreetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldStreetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStreetNameActionPerformed

    private void fieldNUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNUIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNUIDActionPerformed

    private void fieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFirstNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField fieldAprtNumber;
    private javax.swing.JTextField fieldCity;
    private javax.swing.JTextField fieldCollegeName;
    private javax.swing.JTextField fieldEmailAddress;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldNUID;
    private javax.swing.JTextField fieldPhoneNumber;
    private javax.swing.JTextField fieldStreetName;
    private javax.swing.JTextField fieldZipCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel viewAprtNumber;
    private javax.swing.JLabel viewCity;
    private javax.swing.JLabel viewCollegeName;
    private javax.swing.JLabel viewEmailAddress;
    private javax.swing.JLabel viewFirstName;
    private javax.swing.JLabel viewLastName;
    private javax.swing.JLabel viewNUID;
    private javax.swing.JLabel viewPhoneNumber;
    private javax.swing.JLabel viewStreetName;
    private javax.swing.JLabel viewZipCode;
    // End of variables declaration//GEN-END:variables
}
