/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import Model.*;


/**
 *
 * @author xyh10
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    Application application;
    
    
    public Main() {
        initComponents();
        application = new Application();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        createBtn = new javax.swing.JButton();
        viewSignBtn = new javax.swing.JButton();
        mdCatalogBtn = new javax.swing.JButton();
        assignBtn = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setBackground(new java.awt.Color(0, 255, 255));
        controlPanel.setMinimumSize(new java.awt.Dimension(200, 600));
        controlPanel.setPreferredSize(new java.awt.Dimension(150, 300));
        controlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createBtn.setText("create observation");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        controlPanel.add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 130, 30));

        viewSignBtn.setText("view vital sign");
        viewSignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSignBtnActionPerformed(evt);
            }
        });
        controlPanel.add(viewSignBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 130, 30));

        mdCatalogBtn.setText("medicine catalog");
        mdCatalogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdCatalogBtnActionPerformed(evt);
            }
        });
        controlPanel.add(mdCatalogBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 130, 30));

        assignBtn.setText("Assign medicine");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });
        controlPanel.add(assignBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 130, 30));

        jSplitPane1.setLeftComponent(controlPanel);

        displayPanel.setBackground(new java.awt.Color(153, 255, 153));
        displayPanel.setMinimumSize(new java.awt.Dimension(300, 500));
        displayPanel.setPreferredSize(new java.awt.Dimension(300, 500));
        displayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jSplitPane1.setRightComponent(displayPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new CreatePanel(application));
    }//GEN-LAST:event_createBtnActionPerformed

    private void viewSignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSignBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new ViewPanel(application));
    }//GEN-LAST:event_viewSignBtnActionPerformed

    private void mdCatalogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdCatalogBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new MedicineCatalogPanel(application));
    }//GEN-LAST:event_mdCatalogBtnActionPerformed

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new MedicineAssignment(application));
    }//GEN-LAST:event_assignBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignBtn;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton createBtn;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton mdCatalogBtn;
    private javax.swing.JButton viewSignBtn;
    // End of variables declaration//GEN-END:variables
}
