/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.*;

/**
 *
 * @author xyh10
 */
public class MedicineAssignment extends javax.swing.JPanel {

    /**
     * Creates new form MedicineAssignment
     */
    Application application;
    public MedicineAssignment() {
        initComponents();
    }

    public MedicineAssignment(Application application) {
        initComponents();
        this.application = application;
        loadData();
    }
    
    public void loadData(){
        for(Observation ob:application.getHistory().getVitalSignHistory()){
            ObservationBox.addItem(ob.toString());
//              ObservationBox.addItem(ob);
        }
        
        for(Medicine md:application.getCatalog().getMedicineCatalog()){
            MedicineBox.addItem(md.toString());
        }
        
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ObservationBox = new javax.swing.JComboBox<>();
        MedicineBox = new javax.swing.JComboBox<>();
        AssignBtn = new javax.swing.JButton();
        showChanges = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ObservationBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ObservationBoxItemStateChanged(evt);
            }
        });
        add(ObservationBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 130, 149, -1));

        add(MedicineBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 130, 140, -1));

        AssignBtn.setText("Assign");
        AssignBtn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AssignBtnStateChanged(evt);
            }
        });
        AssignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignBtnActionPerformed(evt);
            }
        });
        add(AssignBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        showChanges.setText(" ");
        showChanges.setOpaque(true);
        showChanges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showChangesMouseClicked(evt);
            }
        });
        add(showChanges, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 110, 20));

        jLabel1.setText("Observation");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel2.setText("Medicine");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel3.setText("cur Medicine");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void AssignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignBtnActionPerformed
        // TODO add your handling code here:
//        System.out.println(ObservationBox.getSelectedItem());
        Observation ob = application.getHistory().findObservation(Integer.parseInt((String) ObservationBox.getSelectedItem()));
        Medicine md = application.getCatalog().findMedicine((String) MedicineBox.getSelectedItem());
        
        ob.setMedicine(md);
        

        showChanges.setText(ob.getMedicine().getMedicineName());


    }//GEN-LAST:event_AssignBtnActionPerformed

    private void showChangesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showChangesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_showChangesMouseClicked

    private void AssignBtnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AssignBtnStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_AssignBtnStateChanged

    private void ObservationBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ObservationBoxItemStateChanged
        // TODO add your handling code here:
        Observation ob = application.getHistory().findObservation(Integer.parseInt((String) ObservationBox.getSelectedItem()));
        
        
        if(ob.getMedicine()!= null){
            showChanges.setText(ob.getMedicine().getMedicineName());
//            showChanges.setText()
        }
    }//GEN-LAST:event_ObservationBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignBtn;
    private javax.swing.JComboBox<String> MedicineBox;
    private javax.swing.JComboBox<String> ObservationBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel showChanges;
    // End of variables declaration//GEN-END:variables
}
