/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import Model.*;
import javax.swing.JOptionPane;
/**
 *
 * @author xyh10
 */
public class ReadPane extends javax.swing.JPanel {

    /**
     * Creates new form ReadPane
     */
    private DeliveryPackage deliveryPackage;
    public ReadPane() {
        initComponents();
    }
    
    public ReadPane(DeliveryPackage deliveryPackage){
        initComponents();
        
        this.deliveryPackage = deliveryPackage;
        displayPackageDetails();
        
    }

    public void displayPackageDetails(){
        packageID.setText(deliveryPackage.getPackageID()+"");
        packageWeight.setText(deliveryPackage.getPackageWeight() + "");
//        productID.setText(deliveryPackage.getProduct().getProductID() + "");
//        productName.setText(""+ deliveryPackage.getProduct().getProductName());
//        productPrice.setText(""+ deliveryPackage.getProduct().getPrice());
        customerID.setText(""+ deliveryPackage.getCustomer().getCustomerID());
        customerName.setText(deliveryPackage.getCustomer().getFullName());
        
          
        for(Product p:deliveryPackage.getProductlist()){
            jComboBox1.addItem("" + p.getProductID());
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        packageID = new javax.swing.JTextField();
        packageWeight = new javax.swing.JTextField();
        productID = new javax.swing.JTextField();
        productName = new javax.swing.JTextField();
        productPrice = new javax.swing.JTextField();
        customerName = new javax.swing.JTextField();
        customerID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        showBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(packageID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 110, 30));
        add(packageWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 110, 30));
        add(productID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 110, 30));

        productName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameActionPerformed(evt);
            }
        });
        add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 110, 30));
        add(productPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 110, 30));
        add(customerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 110, 30));
        add(customerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 110, 30));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("packageID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("packageWeight");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("productID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("productName");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("productPrice");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("full Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("customerID");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- choose an product --" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 190, 30));

        showBtn.setText("show");
        showBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBtnActionPerformed(evt);
            }
        });
        add(showBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void productNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void showBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBtnActionPerformed
        // TODO add your handling code here:
        String  pid =  (String) jComboBox1.getSelectedItem();
        
        Product p = deliveryPackage.findProduct(Integer.parseInt(pid));

        productID.setText(p.getProductID() + "");
        productName.setText(p.getProductName());
        productPrice.setText("" + p.getPrice());
    
    }//GEN-LAST:event_showBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField customerID;
    private javax.swing.JTextField customerName;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField packageID;
    private javax.swing.JTextField packageWeight;
    private javax.swing.JTextField productID;
    private javax.swing.JTextField productName;
    private javax.swing.JTextField productPrice;
    private javax.swing.JButton showBtn;
    // End of variables declaration//GEN-END:variables
}
