/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.ManagerWorkArea;


import Business.*;
import javax.swing.table.DefaultTableModel;
import Customer.*;
import javax.swing.JOptionPane;

/**
 *
 * @author xyh10
 */
public class CustomerManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerManagementPanel
     */
    Business business;
    UserAccount userAccount;
    DefaultTableModel tableModel;
    
    public CustomerManagementPanel() {
        initComponents();
    }
    
    public CustomerManagementPanel(Business business, UserAccount userAccount) {
        initComponents();
        this.business = business;
        this.userAccount = userAccount;
        tableModel = (DefaultTableModel) customerTabel.getModel();
        populate();
    }
    
    
    public void populate(){
        tableModel.setRowCount(0);
        
        for(Customer c:business.getCustomerDirectory().getCustomerList()){
//            System.out.println(c.getPersonID());
           UserAccount ua = business.getUserAccountDirectory().findByID(c.getPersonID());
            
            Object[] row = new Object[4];
            row[0] = c.getPersonID();
            row[1] = c.getName();
            row[2] = ua.getUsername();
            row[3] = ua.getPassword();
            
            tableModel.addRow(row);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldAge = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JTextField();
        fieldName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTabel = new javax.swing.JTable();
        addCustomerBtn = new javax.swing.JButton();
        fieldUserName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fieldAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAgeActionPerformed(evt);
            }
        });
        add(fieldAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 120, 30));
        add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 120, 30));

        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });
        add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 120, 30));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("username");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("age");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        customerTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customerTabel);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        addCustomerBtn.setText("Add Customer");
        addCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerBtnActionPerformed(evt);
            }
        });
        add(addCustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));
        add(fieldUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAgeActionPerformed

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    private void addCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerBtnActionPerformed
        // TODO add your handling code here:
        UserAccountDirectory uad = business.getUserAccountDirectory();
        
        if(uad.UserAccountExist(fieldUserName.getText(),fieldPassword.getText() , "Customer")){
            JOptionPane.showMessageDialog(null, "Sorry credentials are taken.");
        }else{
            UserAccount ua = business.getUserAccountDirectory().createUserAccount(fieldUserName.getText(),fieldPassword.getText(), "Customer" );
            business.getCustomerDirectory().createCustomer(ua.getAccountID(), fieldName.getText(),fieldAge.getText() );
            populate();
        }
    }//GEN-LAST:event_addCustomerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerBtn;
    private javax.swing.JTable customerTabel;
    private javax.swing.JTextField fieldAge;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPassword;
    private javax.swing.JTextField fieldUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
