/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.ManagerWorkArea;

import Business.Business;
import Business.UserAccount;
import javax.swing.table.DefaultTableModel;
import Services.*;
import Restaurant.*;

/**
 *
 * @author xyh10
 */
public class OrderManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderManagementPanel
     */
    Business business;
    UserAccount userAccount;
    DefaultTableModel tableModel;
    
    
    public OrderManagementPanel() {
        initComponents();
    }    
    
    public OrderManagementPanel(Business business, UserAccount userAccount) {
        initComponents();
        this.business = business;
        this.userAccount = userAccount;
        tableModel = (DefaultTableModel) orderTable.getModel();
        display();
    }
    
    public void display(){
        // set table content
        tableModel.setRowCount(0);
        
        for(Order o:business.getMasterOrderDirectory().getOrderList()){
            Object[] row = new Object[3];
            
//            row[0] = o.getOrderID();
            row[0] = o;
            row[1] = o.getC().toString();
            
            row[2] = o.getAgent() == null ? "":o.getAgent().toString();
            
            tableModel.addRow(row);    
        }
        
        
        // set combo box
        
        for(DeliveryAgent a:business.getDeliveryAgentDirectory().getAgentList()){
//            agentCombox.addItem(a.getPersonID());
            agentCombox.addItem(a);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        agentCombox = new javax.swing.JComboBox();
        assignBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Customer", "Delivery Agent"
            }
        ));
        jScrollPane1.setViewportView(orderTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 590, 320));

        agentCombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentComboxActionPerformed(evt);
            }
        });
        add(agentCombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 300, -1));

        assignBtn.setText("Assign");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });
        add(assignBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here:
        DeliveryAgent a = (DeliveryAgent) agentCombox.getSelectedItem();
//        DeliveryAgent a =  business.getDeliveryAgentDirectory().findByID((String) agentCombox.getSelectedItem());
        
        Order o = (Order) orderTable.getValueAt(orderTable.getSelectedRow(), 0);
        
        o.setAgent(a);
        a.addOrder(o);
        
        display();
        
    }//GEN-LAST:event_assignBtnActionPerformed

    private void agentComboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentComboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agentComboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox agentCombox;
    private javax.swing.JButton assignBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderTable;
    // End of variables declaration//GEN-END:variables
}
